[package]
name = "mqtt-hostname-online"
description = "Publishes the online status of the device on the MQTT topic <hostname>/connected"
version = "0.1.0"
license = "MIT"
authors = ["EdJoPaTo <mqtt-hostname-online-rust@edjopato.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hostname = "0.3"
rumqttc = "0.5"

[dependencies.clap]
version = "2"
features = ["wrap_help"]
